# Generated by Django 6.0.3 on 2026-04-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=100)),
                ('anime_description', models.TextField()),
                ('anime_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
