# Generated by Django 6.0.3 on 2026-04-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_image',
            field=models.ImageField(upload_to='anime'),
        ),
    ]
